version: '3'
services:
    main:
        build:
            context: .
        command: "php artisan config:cache"
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: job_portal
            MYSQL_USER: kuro
            MYSQL_PASSWORD: senpai
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
