version: '3'
services:
    main:
        build:
            context: .
        command: "php artisan config:cache"
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
      platform: linux/x86_64
      image: mysql:8.0
      container_name: mysql

      volumes:
        - ./storage/dbdata:/var/lib/mysql
      # restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: job
        MYSQL_USER: kuro
        MYSQL_PASSWORD: senpai
      ports:
          - 3306:3306

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - '8080:80'
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: password
